PROGRAM Average_sum_of_nums
IMPLICIT NONE
REAL:: AVERAGE
INTEGER :: I,SUM
WRITE (*,'(a)')'FULL NAME CS2019XXXXXX'
SUM=0.0
DO I=5,100,5
       WRITE (*,*)'MULTIPLE 5 IS :',I
  SUM=SUM+I
   END DO
  WRITE (*,*)'SUM:',SUM
  AVERAGE = SUM/20
  WRITE (*,*)'AVERAGE:',AVERAGE
END PROGRAM Average_sum_of_nums
