PROGRAM TO_CALCULATE_QUADRATIC_EQUATION
IMPLICIT NONE
REAL::a,b,c,d,X1,X2
WRITE (*,'(a)')'FULL NAME CS2019XXXXXX'
WRITE (*,'(a)')'ENTER VALUE FOR A'
READ(*,10)a
10 FORMAT(I2)
WRITE (*,'(a)')'ENTER VALUE FOR B'
READ(*,20)b
20 FORMAT(I2)
WRITE (*,'(a)')'ENTER VALUE FOR C'
READ(*,30)c
30 FORMAT(F4.2)
X1=-b-SQRT((b**2)-4*a*c)/2*a
X2=-b+SQRT((b**2)-4*a*c)/2*a
WRITE (*,*)'X1',X1,'X2',X2
STOP
END PROGRAM TO_CALCULATE_QUADRATIC_EQUATION
