PROGRAM SERIES
IMPLICIT NONE
REAL ::SUM
INTEGER ::J,A
WRITE (*,'(a)')'OLAYIWOLA OLADIPUPO BUKUNMI CS20190201659'
SUM=0.0
DO J= 1,99,2
SUM=SUM+1.0/FLOAT(J)
A= 1
  END DO
WRITE (*,*)'sum =',SUM
END PROGRAM SERIES

